Models
Let-s-Snack/Spring_NoSQL pull request #8
Opened 2024-10-02 00:07 UTC by Gustavo-Teotonio

Fazendo o PR dos arquivos do model de Persons

2024-10-02 01:59 UTC, PedroSchettini requested changes

2024-10-02 01:59 UTC, PedroSchettini commented on src/main/java/org/example/spring_nosql/Model/Coments.java
> +    @Schema(name = "Comentário sobre a receita", example = "Receita muito boa!")
colocar limite de 200 caracteres

2024-10-02 01:59 UTC, PedroSchettini commented on src/main/java/org/example/spring_nosql/Model/DirectionsWeek.java
> +    @Schema(description = "ID da receita da semana", example = "") // Adicionar exemplo
faltou example

2024-10-02 01:59 UTC, PedroSchettini commented on src/main/java/org/example/spring_nosql/Model/DirectionsWeek.java
> +    private String recipesId;
Deveria ter objectId, já que todos estão dessa forma

2024-10-02 01:59 UTC, PedroSchettini commented on src/main/java/org/example/spring_nosql/Controller/GenderController.java
por que tirou essa parte?

2024-10-02 01:59 UTC, PedroSchettini commented on src/main/java/org/example/spring_nosql/Controller/PersonsController.java
> +    public ResponseEntity<?> personFavoriteById(@Parameter(description = "Inserir ID do usuário para encontrar suas receitas da semana") @PathVariable String id){
Texto incorreto, seria receitas favoritadas. e não receitas da semana

2024-10-02 01:59 UTC, PedroSchettini commented on src/main/java/org/example/spring_nosql/Controller/PersonsController.java
> +    @GetMapping("/personWishlist/{id}")
favorites e wishlist não é a mesma coisa?

2024-10-02 01:59 UTC, PedroSchettini commented on src/main/java/org/example/spring_nosql/Controller/PersonsController.java
> +    /*@GetMapping("/personShoppingList/{id}")
por que está comentado?

2024-10-02 01:59 UTC, PedroSchettini commented on src/main/java/org/example/spring_nosql/Controller/PersonsController.java
> +    @Operation(summary = "Inserir Usuário", description = "Faz a inserção do gênero passado no body")
description errado, seria a inserção do usuário

2024-10-02 01:59 UTC, PedroSchettini commented on src/main/java/org/example/spring_nosql/Controller/PersonsController.java
> +                person.setId(new ObjectId());
já irá criar sem a chance de ser igual a algum do banco?

2024-10-02 01:59 UTC, PedroSchettini commented on src/main/java/org/example/spring_nosql/Controller/PersonsController.java
> +                if (updatedValues.containsKey("favorites")) {
wishlist e favorites são a mesma coisa

2024-10-02 01:59 UTC, PedroSchettini commented on src/main/java/org/example/spring_nosql/Controller/PersonsController.java
> +                if (updatedValues.containsKey("deactivationDate")) {
deactivationDate foi retirado da modelagem

2024-10-02 01:59 UTC, PedroSchettini commented on src/main/java/org/example/spring_nosql/Model/DirectionsWeek.java
> +    @Schema(description = "Data de criação do usuário", example = "2024/08/27")
criação de usuário não, receita da semana

2024-10-02 01:59 UTC, PedroSchettini commented on src/main/java/org/example/spring_nosql/Model/Favorites.java
> +    private String recipesId;
deveria ser objectId por questão de padrão

2024-10-02 01:59 UTC, PedroSchettini commented on src/main/java/org/example/spring_nosql/Model/Gender.java
por que foi retirado?

2024-10-02 01:59 UTC, PedroSchettini commented on src/main/java/org/example/spring_nosql/Model/Wishlist.java
> +    private String recipesId;
deixar como objectId por questão de padrão

2024-10-02 01:59 UTC, PedroSchettini commented on src/main/java/org/example/spring_nosql/Model/ShoppingList.java
> +    private String recipesId;
deixar como objectId por questão de padrão

2024-10-02 01:59 UTC, PedroSchettini commented on src/main/java/org/example/spring_nosql/Model/Wishlist.java
> +    @Schema(description = "ID da receita da wishlist", example = "") // Adicionar exemplo
adicionar example

2024-10-02 01:59 UTC, PedroSchettini commented on src/main/java/org/example/spring_nosql/Model/ShoppingList.java
> +    @Schema(description = "ID da receita da shopping list", example = "") // Adicionar exemplo
adicionar example

2024-10-02 01:59 UTC, PedroSchettini commented on src/main/java/org/example/spring_nosql/Model/ShoppingList.java
> +    @Schema(description = "Id dos ingredientes salvos", example = "") // Adicionar exemplo
adicionar example

2024-10-02 01:59 UTC, PedroSchettini commented on src/main/java/org/example/spring_nosql/Model/Restrictions.java
>      @Schema(description = "URL da Photo", example = "") //Adicionar exemplo de URL de foto
adicionar example

2024-10-02 01:59 UTC, PedroSchettini commented on src/main/java/org/example/spring_nosql/Model/PersonsRestrictions.java
> +    @Schema(name = "URL da Photo", example = "") //Adicionar exemplo de URL de foto
adicionar example

2024-10-02 01:59 UTC, PedroSchettini commented on src/main/java/org/example/spring_nosql/Model/PersonsRestrictions.java
> +    private String restrictionId;
colocar como objectId por questão de padrão

2024-10-02 01:59 UTC, PedroSchettini commented on src/main/java/org/example/spring_nosql/Model/Persons.java
retirar comentários de "adicionar exemplo"

2024-10-02 01:59 UTC, PedroSchettini commented on src/main/java/org/example/spring_nosql/Model/IngredientsShoppingList.java
> +    @Schema(description = "Id da receita ", example = "") //adicionar exemplo
adicionar example

2024-10-02 01:59 UTC, PedroSchettini commented on src/main/java/org/example/spring_nosql/Service/PersonsService.java
> +    /*//Fazendo um método para retornar uma lista das receitas e dos ingredientes do usuário
por que está comentado?

2024-10-02 11:51 UTC, Gustavo-Teotonio reviewed
Alterações feitas conforme solicitado!

2024-10-02 11:51 UTC, Gustavo-Teotonio commented on src/main/java/org/example/spring_nosql/Controller/GenderController.java
Porque o document de gender não existe mais, nós resumimos o mesmo dentro do document de persons

2024-10-02 11:51 UTC, Gustavo-Teotonio commented on src/main/java/org/example/spring_nosql/Model/DirectionsWeek.java
> +    @Schema(description = "ID da receita da semana", example = "") // Adicionar exemplo
Feito

2024-10-02 11:51 UTC, Gustavo-Teotonio commented on src/main/java/org/example/spring_nosql/Model/Coments.java
> +    @Schema(name = "Comentário sobre a receita", example = "Receita muito boa!")
Feito!

2024-10-02 11:51 UTC, Gustavo-Teotonio commented on src/main/java/org/example/spring_nosql/Model/DirectionsWeek.java
> +    @Schema(description = "Data de criação do usuário", example = "2024/08/27")
Feito!

2024-10-02 11:51 UTC, Gustavo-Teotonio commented on src/main/java/org/example/spring_nosql/Model/Favorites.java
> +    private String recipesId;
Conforme conversamos vamos deixar os ids das subclasses como string

2024-10-02 11:51 UTC, Gustavo-Teotonio commented on src/main/java/org/example/spring_nosql/Model/Gender.java
Conforme foi falado acima, o CRUD de gender não existe mais pois nos retiramos o document da nossa estrutura, sendo inserido em Persons

2024-10-02 11:51 UTC, Gustavo-Teotonio commented on src/main/java/org/example/spring_nosql/Model/IngredientsShoppingList.java
> +    @Schema(description = "Id da receita ", example = "") //adicionar exemplo
Feito!

2024-10-02 11:51 UTC, Gustavo-Teotonio commented on src/main/java/org/example/spring_nosql/Model/Persons.java
Feito

2024-10-02 11:51 UTC, Gustavo-Teotonio commented on src/main/java/org/example/spring_nosql/Model/PersonsRestrictions.java
> +    private String restrictionId;
Conforme conversamos deixamos por padrão o ID das subclasses como string

2024-10-02 11:51 UTC, Gustavo-Teotonio commented on src/main/java/org/example/spring_nosql/Model/PersonsRestrictions.java
> +    @Schema(name = "URL da Photo", example = "") //Adicionar exemplo de URL de foto
Feito!

2024-10-02 11:51 UTC, Gustavo-Teotonio commented on src/main/java/org/example/spring_nosql/Model/Restrictions.java
>      @Schema(description = "URL da Photo", example = "") //Adicionar exemplo de URL de foto
Feito!

2024-10-02 11:51 UTC, Gustavo-Teotonio commented on src/main/java/org/example/spring_nosql/Model/ShoppingList.java
> +    @Schema(description = "ID da receita da shopping list", example = "") // Adicionar exemplo
Feito!

2024-10-02 11:51 UTC, Gustavo-Teotonio commented on src/main/java/org/example/spring_nosql/Model/ShoppingList.java
> +    private String recipesId;
Conforme conversamos deixamos por padrão o ID das subclasses como string

2024-10-02 11:51 UTC, Gustavo-Teotonio commented on src/main/java/org/example/spring_nosql/Model/ShoppingList.java
> +    @Schema(description = "Id dos ingredientes salvos", example = "") // Adicionar exemplo
Feito!

2024-10-02 11:51 UTC, Gustavo-Teotonio commented on src/main/java/org/example/spring_nosql/Model/Wishlist.java
> +    @Schema(description = "ID da receita da wishlist", example = "") // Adicionar exemplo
Feito

2024-10-02 11:51 UTC, Gustavo-Teotonio commented on src/main/java/org/example/spring_nosql/Model/Wishlist.java
> +    private String recipesId;
Conforme conversamos deixamos por padrão o ID das subclasses como string

2024-10-02 11:51 UTC, Gustavo-Teotonio commented on src/main/java/org/example/spring_nosql/Service/PersonsService.java
> +    /*//Fazendo um método para retornar uma lista das receitas e dos ingredientes do usuário
Conforme conversamos estava dando alguns erros na conversão do objeto do mongo para o java, e como eu já estava desenvolvendo a alguns dias essa tarefa nos deixamos de stand by para focarmos em outras

2024-10-05 19:18 UTC, PedroSchettini approved these changes

2024-10-05 19:23 UTC, merged